@startuml

AggregationController -> AggregationService
AggregationService -> ShipmentTask ++ #red: start
ShipmentTask --> AggregationService --#red: done
AggregationService -> TrackingTas ++ #red: start
TrackingTas --> AggregationService --#red: done
AggregationService -> PricingTask ++ #red: start
PricingTask --> AggregationService --#red: done


@enduml